// Trooth Social Independent — Live Video v1
(function(){
  var active={channel:null,stream:null,pc:new Map(),id:null,role:null,hostId:null};
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
  function modal(){var x=document.getElementById('troothLiveModal');if(x)return x; x=document.createElement('div');x.id='troothLiveModal';x.innerHTML='<div class="tl-backdrop"></div><div class="tl-box"><button class="tl-close" aria-label="Close">×</button><h2>🔴 Trooth Live</h2><div id="tlStatus">Loading live streams…</div><div class="tl-actions"><button id="tlStart">Start Live</button><button id="tlJoin">Join Live</button></div><div id="tlVideoWrap"><video id="tlVideo" autoplay playsinline controls></video></div><div id="tlList"></div></div>';document.body.appendChild(x);x.querySelector('.tl-close').onclick=close;x.querySelector('.tl-backdrop').onclick=close;return x}
  function css(){if(document.getElementById('troothLiveCss'))return;var s=document.createElement('style');s.id='troothLiveCss';s.textContent='#troothLiveModal{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center}.tl-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.65)}.tl-box{position:relative;width:min(92vw,620px);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:18px;box-shadow:0 20px 60px rgba(0,0,0,.3)}.tl-close{position:absolute;right:12px;top:8px;border:0;background:#eee;border-radius:50%;width:34px;height:34px;font-size:24px}.tl-actions{display:flex;gap:8px;margin:12px 0}.tl-actions button,.tl-item button{border:0;border-radius:10px;padding:10px 14px;background:#18a957;color:#fff;font-weight:700}.tl-item{display:flex;justify-content:space-between;gap:10px;align-items:center;border:1px solid #e2e8e4;padding:10px;border-radius:12px;margin:8px 0}.tl-item small{display:block;color:#68756e}.tl-item button{background:#1677d2}.tl-video{width:100%}#tlVideo{width:100%;max-height:60vh;background:#111;border-radius:12px;display:none}';document.head.appendChild(s)}
  function status(t){var e=document.getElementById('tlStatus');if(e)e.textContent=t}
  async function sb(){if(window.troothSupabase)return window.troothSupabase;throw new Error('Trooth connection is not ready.')}
  async function send(ch,event,payload){return ch.send({type:'broadcast',event:event,payload:payload})}
  async function subscribe(ch){var s=await sb();await s.realtime.setAuth();return new Promise(function(resolve,reject){ch.subscribe(function(st,err){if(st==='SUBSCRIBED')resolve();else if(st==='CHANNEL_ERROR'||st==='TIMED_OUT')reject(err||new Error(st))})})}
  async function start(){var s=await sb(),u=(await s.auth.getUser()).data.user;if(!u){location.href='auth.html';return}var title=prompt('Live title:','Trooth Live')||'Trooth Live';var r=await s.from('live_streams').insert({host_user_id:u.id,title:title,status:'live'}).select('id').single();if(r.error)throw r.error;active.id=r.data.id;active.role='host';active.hostId=u.id;active.stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});var v=document.getElementById('tlVideo');v.srcObject=active.stream;v.style.display='block';active.channel=s.channel('live:'+active.id,{config:{private:true}});active.channel.on('broadcast',{event:'join'},async function(p){var viewer=p.payload&&p.payload.viewer;if(!viewer)return;var pc=new RTCPeerConnection();active.pc.set(viewer,pc);active.stream.getTracks().forEach(function(t){pc.addTrack(t,active.stream)});pc.onicecandidate=function(e){if(e.candidate)send(active.channel,'ice',{to:viewer,from:u.id,candidate:e.candidate})};var offer=await pc.createOffer();await pc.setLocalDescription(offer);await send(active.channel,'offer',{to:viewer,from:u.id,sdp:offer})});active.channel.on('broadcast',{event:'answer'},async function(p){var d=p.payload||{},pc=active.pc.get(d.from);if(pc&&d.to===u.id)await pc.setRemoteDescription(d.sdp)});active.channel.on('broadcast',{event:'ice'},async function(p){var d=p.payload||{},pc=active.pc.get(d.from);if(pc&&d.to===u.id&&d.candidate)try{await pc.addIceCandidate(d.candidate)}catch(e){}});await subscribe(active.channel);status('You are live. Waiting for viewers…');document.getElementById('tlStart').textContent='End Live';document.getElementById('tlStart').onclick=end}
  async function join(id){var s=await sb(),u=(await s.auth.getUser()).data.user;if(!u){location.href='auth.html';return}active.id=id;active.role='viewer';active.hostId=null;active.channel=s.channel('live:'+id,{config:{private:true}});active.channel.on('broadcast',{event:'offer'},async function(p){var d=p.payload||{};if(d.to!==u.id)return;active.hostId=d.from;var pc=new RTCPeerConnection();active.pc.set(d.from,pc);pc.ontrack=function(e){var v=document.getElementById('tlVideo');v.srcObject=e.streams[0];v.style.display='block'};pc.onicecandidate=function(e){if(e.candidate)send(active.channel,'ice',{to:d.from,from:u.id,candidate:e.candidate})};await pc.setRemoteDescription(d.sdp);var ans=await pc.createAnswer();await pc.setLocalDescription(ans);await send(active.channel,'answer',{to:d.from,from:u.id,sdp:ans})});active.channel.on('broadcast',{event:'ice'},async function(p){var d=p.payload||{},pc=active.pc.get(d.from);if(pc&&d.to===u.id&&d.candidate)try{await pc.addIceCandidate(d.candidate)}catch(e){}});await subscribe(active.channel);await send(active.channel,'join',{viewer:u.id});status('Joining live…')}
  async function list(){var s=await sb(),r=await s.from('live_streams').select('id,title,host_user_id,created_at').eq('status','live').order('created_at',{ascending:false}).limit(20),el=document.getElementById('tlList');if(r.error){status(r.error.message);return}if(!r.data.length){el.innerHTML='<p>No live streams right now.</p>';return}el.innerHTML=r.data.map(function(x){return '<div class="tl-item"><div><b>'+esc(x.title)+'</b><small>'+new Date(x.created_at).toLocaleString()+'</small></div><button data-id="'+x.id+'">Join</button></div>'}).join('');el.querySelectorAll('button').forEach(function(b){b.onclick=function(){join(b.dataset.id).catch(function(e){status('Live join failed: '+e.message)})}})}
  async function end(){try{var s=await sb();if(active.stream)active.stream.getTracks().forEach(function(t){t.stop()});active.pc.forEach(function(pc){pc.close()});active.pc.clear();if(active.id&&active.role==='host')await s.from('live_streams').update({status:'ended',ended_at:new Date().toISOString()}).eq('id',active.id);if(active.channel)await s.removeChannel(active.channel)}finally{active={channel:null,stream:null,pc:new Map(),id:null,role:null,hostId:null};status('Live ended.');document.getElementById('tlVideo').style.display='none';document.getElementById('tlStart').textContent='Start Live';document.getElementById('tlStart').onclick=function(){start().catch(function(e){status('Live start failed: '+e.message)})};document.getElementById('tlList').innerHTML=''}}
  async function open(){css();var m=modal();m.style.display='flex';document.getElementById('tlStart').onclick=function(){start().catch(function(e){status('Live start failed: '+e.message)})};document.getElementById('tlJoin').onclick=function(){list().catch(function(e){status(e.message)})};await list().catch(function(e){status(e.message)})}
  function close(){var m=document.getElementById('troothLiveModal');if(m)m.style.display='none'}
  window.TroothLive={open:open,end:end};
})();